FROM gradle:8.4-jdk17 as builder
USER root
COPY . .
RUN gradle --no-daemon build

FROM gcr.io/distroless/java17
ENV JAVA_TOOL_OPTIONS -XX:+ExitOnOutOfMemoryError
ENV SPRING_PROFILES_ACTIVE=minikube
COPY --from=builder /home/gradle/build/libs/fint-core-provider-gateway-*.jar /data/app.jar
CMD ["/data/app.jar"]
