version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  provider-redis:
    image: redis:6.2
    container_name: provider-redis
    ports:
      - "6380:6379"
    volumes:
      - provider-redis-data:/data
    command: [ "redis-server" ]
    restart: always

  topic-redis:
    image: redis:6.2
    container_name: topic-redis
    ports:
      - "6379:6379"
    volumes:
      - topic-redis-data:/data
      - ./topic-topic-redis.conf:/usr/local/etc/redis/topic-redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/topic-redis.conf" ]
    restart: always

networks:
  broker-kafka:
    driver: bridge

volumes:
  provider-redis-data:
    driver: local

  topic-redis-data:
    driver: local
