server:
  port: 8085
  servlet:
    context-path: /provider

fint:
  metamodel:
    base-url: http://localhost:8082
  kafka:
    enable-ssl: false

novari:
  kafka:
    application-id: provider
    default-replicas: 1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: provider

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
