apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-beta-vault/items/aiven-kafka"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-core-provider-gateway-service
  name: fint-core-provider-gateway-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-core-provider-gateway-service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-core-provider-gateway-service
  #namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`beta.felleskomponent.no`) && PathPrefix(`/provider`)
      kind: Rule
      services:
        - name: fint-core-provider-gateway-service
          #namespace: default
          port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-core-provider-gateway
  name: fint-core-provider-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-core-provider-gateway
  template:
    metadata:
      labels:
        io.kompose.service: fint-core-provider-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "provider/actuator/prometheus"
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-core-provider-gateway:dummy
          name: fint-core-provider-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "1152Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: '-XX:+ExitOnOutOfMemoryError -Xmx3G -verbose:gc'
            - name: spring.webflux.base-path
              value: /provider
            - name: spring.codec.max-in-memory-size
              value: 200MB
            - {name: server.tomcat.max-threads, value: '400'}
            - {name: server.tomcat.max-connections, value: '30000'}
            - {name: server.netty.connection-timeout, value: '600000'}
            - {name: server.connection-timeout, value: '600000'}