apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-provider-gateway-daniel
  namespace: fint-core
spec:
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx9700m'
#    - name: novari.kafka.producer.linger
#      value: "100ms"
#    - name: novari.kafka.producer.batch-size
#      value: "512KB"
    - name: FINT_PROVIDER_KAFKA_ENTITY_PARTITIONS
      value: "12"
    - name: spring.webflux.base-path
      value: "/coretest/provider"
  ingress:
    routes:
      - host: beta.felleskomponent.no
        path: /coretest/provider
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus
  resources:
    limits:
      memory: 10Gi
      cpu: "5"
    requests:
      memory: "128Mi"
      cpu: "100m"