apiVersion: v1
data:
  JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -Xmx3GB
  TZ: Europe/Oslo
  fint.org-id: fintlabs.no
  logging.level.no.fintlabs.event: debug
  server.connection-timeout: 600000
  server.netty.connection-timeout: 600000
  server.tomcat.max-connections: 30000
  server.tomcat.max-threads: 400
  spring.codec.max-in-memory-size: 200MB
  spring.webflux.base-path: /provider
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-provider-gateway
  namespace: fint-core
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-provider-gateway
  namespace: fint-core
spec:
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-provider-gateway
  namespace: fint-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
      app.kubernetes.io/name: fint-core-provider-gateway
      app.kubernetes.io/part-of: fint-core
      app.kubernetes.io/version: latest
      fintlabs.no/org-id: fintlabs.no
      fintlabs.no/team: core
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
        app.kubernetes.io/name: fint-core-provider-gateway
        app.kubernetes.io/part-of: fint-core
        app.kubernetes.io/version: latest
        fintlabs.no/org-id: fintlabs.no
        fintlabs.no/team: core
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: fint-core-provider-gateway-kafka
        - configMapRef:
            name: fint-core-provider-gateway
        image: ghcr.io/fintlabs/fint-core-provider-gateway:sha-0000000
        name: fint-core-provider-gateway
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1152Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /credentials
          name: credentials
      restartPolicy: Always
      volumes:
      - name: credentials
        secret:
          secretName: fint-core-provider-gateway-kafka-certificates
---
apiVersion: fintlabs.no/v1alpha1
kind: KafkaUserAndAcl
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-provider-gateway
  namespace: fint-core
spec:
  acls:
  - permission: admin
    topic: '*.fint-core.*'
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs-no
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-provider-gateway
  namespace: fint-core
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`alpha.felleskomponent.no`) && PathPrefix(`/provider`)
    services:
    - name: fint-core-provider-gateway
      port: 8080
