apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fint-core
resources:
  - application.yaml
labels:
  - pairs:
      app.kubernetes.io/name: fint-core-provider-gateway
      app.kubernetes.io/instance: fint-core-provider-gateway_fintlabs_no
      app.kubernetes.io/version: latest
      app.kubernetes.io/component: provider
      app.kubernetes.io/part-of: fint-core
      fintlabs.no/team: core
      fintlabs.no/org-id: fintlabs.no
