name: deploy-to-kubernetes

on:
  push:
    branches: ['CT-509-legg-til-kustomize']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NAMESPACE: fint-core

jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cluster:
          - name: aks-alpha-fint-2021-11-18
          - name: aks-beta-fint-2021-11-23
#          - name: aks-api-fint-2022-02-08
#          - name: aks-pwf-fint-2021-10-20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,enable=true,priority=100,prefix=shaF-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get environment
        uses: actions/github-script@v6
        id: environment
        with:
          script: |
            const a = '${{ matrix.cluster.name }}'.split('-')
            return `${a[1]}`
          result-encoding: string

      - name: Get resource group name
        uses: actions/github-script@v6
        id: rg
        with:
          script: |
            const a = '${{ matrix.cluster.name }}'.split('-')
            return `rg-${a[0]}-${a[1]}`
          result-encoding: string

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2.2
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ steps.environment.outputs.result }}'

      - uses: actions/github-script@v6
        name: Get auth
        id: auth
        with:
          script: |
            const e = '${{ steps.environment.outputs.result }}'.toUpperCase()
            return `secrets.AKS_${e}_FINT_GITHUB`
          result-encoding: string

      - name: Set the target cluster
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result) | toupper] }}"
          cluster-name: ${{ matrix.cluster.name }}
          resource-group: ${{ steps.rg.outputs.result }}

      - name: Deploy
        uses: azure/k8s-deploy@v4.4
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ steps.meta.outputs.tags }}
          namespace: ${{ env.NAMESPACE }}
          action: deploy
